# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'pastekb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pastekb
  pod 'Masonry'

end

target 'pastekbapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pastekbapp
  pod 'Masonry'
  pod 'Toast'

end
