# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Keyboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Keyboard
  pod 'Masonry'

end

target 'PasteKeyboard' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PasteKeyboard
  pod 'Masonry'
  pod 'Toast'

end
